//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailMonitorService
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailRecord
    {
        public int EmailRecordID { get; set; }
        public string EmailSubject { get; set; }
        public string Body { get; set; }
        public string Source { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public bool IsSent { get; set; }
    }
}
